### ISSUE TITLE
Memgraph lab - allow pausing logs scroll

### ISSUE THREAD

**Issue by alex-linx** [memgraph/memgraph-platform#64]
The logs in memgraph lab are constantly scrolling down, which makes it almost impossible to search text in them, or even copy text, because when you select something it already scrolled down.

**Comment by tonilastre** [comment]
Hi @alex-linx, just wanna update you that this issue has been fixed in the Lab v2.8.1: https://memgraph.com/docs/memgraph-lab/changelog#lab-v281---aug-22-2023

When running memgraph-platform, just make sure you use one of the following tags: `latest`, `2.10.2-memgraph2.10.1-lab2.8.1-mage1.10` or `2.10.2-memgraph2.10.1-lab2.8.1`.
