### ISSUE TITLE
Authentication failure when trying to start mgconsole in an existing Docker container after creating a user

### ISSUE THREAD

**Issue by karmenrabar** [memgraph/memgraph-platform#73]
The flow with which authentication failure shows is the following:
```
docker run _container-name_
docker execute -it  _container-name_  mgconsole
CREATE USER ….
docker stop _container-name_
docker start _container-name_ 
docker execute -it  _container-name_  mgconsole
```
--> authentication failure

**Comment by katarinasupe** [comment]
This is not an issue anymore because, by default, Memgraph Platform does not start mgconsole. Since there is a user created, it is expected that the user starts mgconsole like this:
`docker exec -it <CONTAINER_ID/NAME> mgconsole --username <USERNAME> --password <PASSWORD>`
The above code works as expected.
